apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::543531731819:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-A24Q3P5IME1W
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::543531731819:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-31T19:03:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "877"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: f3c855d6-c938-4969-9ca0-373feaf018fa
